// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA22lkv31ecgk5bx0WU58oZraWv4LjdqP8',
    appId: '1:579552087926:web:9857c4406906762087f457',
    messagingSenderId: '579552087926',
    projectId: 'foodora-16cf5',
    authDomain: 'foodora-16cf5.firebaseapp.com',
    storageBucket: 'foodora-16cf5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYJYQ8SytCzXyCBTNpBnR0q7bYzkED7YE',
    appId: '1:579552087926:android:77983999d764869d87f457',
    messagingSenderId: '579552087926',
    projectId: 'foodora-16cf5',
    storageBucket: 'foodora-16cf5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkux80O1Qxafj1vFpRWogtNg8iSksMTbI',
    appId: '1:579552087926:ios:781b97186f1e570887f457',
    messagingSenderId: '579552087926',
    projectId: 'foodora-16cf5',
    storageBucket: 'foodora-16cf5.firebasestorage.app',
    iosBundleId: 'com.example.swiggyUi',
  );
}
